#!/bin/bash

BASE=$(dirname $0)/..
BUILD=/srv/build
IMAGE=$1

qemu-system-or32 -drive if=none,file=$IMAGE,id=hda \
    -device virtio-blk-device,drive=hda \
    -m 2048 -nographic \
    -kernel ${BASE}/linux/vmlinux \
    -net nic,model=opencores_eth -net tap,name=or1k,script=${BASE}/tests/qemu-net-up \
    -fsdev local,id=devel,path=${BASE},security_model=passthrough \
    -device virtio-9p-device,mount_tag=devel,fsdev=devel \
    -fsdev local,id=build,path=${BUILD},security_model=passthrough \
    -device virtio-9p-device,mount_tag=build,fsdev=build
