#!/bin/sh

# You want something like this in your rc.local:
# brctl addbr buildbot-br
# ip addr add 192.168.1.1/24 dev buildbot-br
# ip link set up dev buildbot-br
# 
# /etc/init.d/isc-dhcp-server restart

/sbin/brctl addif buildbot-br $1
/sbin/ip link set up dev $1
