#!/bin/sh

mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
mount -t tmpfs tmpfs /tmp

mkdir /dev/pts
mount -t devpts devpts /dev/pts

mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

hostname openrisc

fsck /dev/vda
mount -o remount,rw /
mkdir -p /home/bluecmd/or1k-devel /srv/build
mount -a

/usr/sbin/sshd

/sbin/ip link set up dev eth0
/sbin/ip link
/sbin/udhcpc

echo "Getting time from NTP ..."
/usr/sbin/ntpd -n -q -p ntp1.sp.se

echo "Startup complete"
