#!/bin/sh

mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
mount -t tmpfs tmpfs /tmp

mkdir /dev/pts
mount -t devpts devpts /dev/pts

mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

/usr/sbin/sshd -Dddd
echo "Startup complete"
